[workspace]
members = [".", "spcasm_derive", "spcasm-web"]

[package]
edition = "2021"
license = "BSD 2-clause"
name = "spcasm"
version = "0.1.0"
build = "build.rs"
default-run = "spcasm"

[lib]
name = "spcasm"
required-features = []

[[bin]]
name = "spcasm"
required-features = ["binaries"]
test = false
bench = false

[[bin]]
name = "brri"
path = "src/brr/interactive.rs"
required-features = ["binaries"]

[features]
default = ["expensive_tests", "binaries"]
test_bootrom = []
binaries = ["dep:clap", "dep:object"]
expensive_tests = []

[dependencies]
object = { version = "0.29.0", features = ["write_core"], optional = true }
serde_variant = "0.1.1"
thiserror = "1.0.30"
lalrpop-util = "0.19"
wav = "1.0.0"
num-traits = "0.2"
num-derive = "0.3"
fixed = "1"
az = "1.2"
arrcat = "0.1"

[build-dependencies]
lalrpop = { version = "0.19", default-features = false }

[dependencies.miette]
features = ["fancy"]
version = "5.3"

[dependencies.serde]
features = ["derive"]
version = "1.0.136"

# Only compile clap for the CLIs.
[dependencies.clap]
version = "3"
optional = true
features = ["derive"]

[dependencies.spcasm_derive]
path = "spcasm_derive"

[profile.release]
opt-level = "s"
lto = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = 2
lto = "thin"
debug-assertions = true

# This is the actual release profile; wasm-pack can't use custom profiles so we reserve "release" for it.
[profile.spasm-release]
inherits = "release"
opt-level = 3
