[workspace]
members = [".", "spcasm_derive", "spcasm-web"]

[package]
name = "spcasm"
description = "A modern, user-friendly SPC700 assembler."
homepage = "https://kleinesfilmroellchen.github.io/spcasm/"
repository = "https://github.com/kleinesfilmroellchen/spcasm"
keywords = ["spc-700", "s-smp", "snes"]
categories = ["compilers", "command-line-utilities", "development-tools", "multimedia::audio"]
authors = ["kleines Filmröllchen <filmroellchen@serenityos.org>"]
version = "0.1.0"
license-file = "LICENSE"

edition = "2021"
rust-version = "1.56"
build = "build.rs"

default-run = "spcasm"

[lib]
name = "spcasm"
required-features = []

[[bin]]
name = "spcasm"
required-features = ["binaries"]
test = false
bench = false

[[bin]]
name = "brr"
path = "src/brr/cli.rs"
required-features = ["binaries"]
test = false
bench = false

[features]
default = ["expensive_tests", "binaries"]
test_bootrom = []
binaries = ["dep:clap", "dep:object"]
expensive_tests = []

[dependencies]
object = { version = "0.29.0", features = ["write_core"], optional = true }
thiserror = "1.0.30"
lalrpop-util = "0.19"
wav = "1.0.0"
num-traits = "0.2"
num-derive = "0.3"
arrcat = "0.1"

[build-dependencies]
lalrpop = { version = "0.19", default-features = false }

[dependencies.miette]
features = ["fancy-no-backtrace"]
version = "5.3"

# Only compile clap for the CLIs.
[dependencies.clap]
version = "4"
optional = true
default-features = false
features = ["derive", "std", "wrap_help", "help", "usage"]

[dependencies.spcasm_derive]
path = "spcasm_derive"

[profile.release]
opt-level = "s"
lto = true
debug-assertions = false
debug = false

[profile.bench]
opt-level = 3
debug = 2
lto = "thin"
debug-assertions = true

# This is the actual release profile; wasm-pack can't use custom profiles so we reserve "release" for it.
[profile.spcasm-release]
inherits = "release"
# If you need ~0.5MiB less binary size, change this to "fat" LTO.
lto = "thin"
opt-level = 3
