[package]
edition = "2021"
license = "BSD 2-clause"
name = "spcasm"
version = "0.1.0"
build = "build.rs"
default-run = "spcasm"

[lib]
name = "spcasm"

[[bin]]
name = "spcasm"
required-features = ["clap"]
test = false
bench = false

[[bin]]
name = "brri"
path = "src/brr/interactive.rs"
required-features = ["clap"]

[features]
default = ["expensive_tests", "clap"]
test_bootrom = []
clap = ["dep:clap"]
expensive_tests = []

[dependencies]
object = { version = "0.28.3", features = ["write_core"] }
serde_variant = "0.1.1"
thiserror = "1.0.30"
lalrpop-util = "0.19"
wav = "1.0.0"
num-traits = "0.2"
num-derive = "0.3"
fixed = "1"
az = "1.2"
arrcat = "0.1"

[build-dependencies]
lalrpop = { version = "0.19", default-features = false }

[dependencies.miette]
features = ["fancy"]
version = "5.3"

[dependencies.serde]
features = ["derive"]
version = "1.0.136"

# Only compile clap for the CLIs.
[dependencies.clap]
version = "3"
optional = true
features = ["derive"]

[dependencies.spcasm_derive]
path = "spcasm_derive"
