[package]
edition = "2021"
license = "BSD 2-clause"
name = "spcasm"
version = "0.1.0"
[dependencies]
object = { version = "0.28.3", features = ["write_core"] }
serde_variant = "0.1.1"
thiserror = "1.0.30"

[dependencies.miette]
features = ["fancy"]
version = "4.6.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.136"

[dependencies.spcasm_derive]
path = "spcasm_derive"
