# https://github.com/linusg/hyper-unspecific-data-parsing-and-graphing-scripts
repository = "."
output = "./hudpags-analysis.json"
commit_sampling = "all"

[logging]
level = "INFO"

[cache]
directory = "./hudpags"

[analyzers.lines_of_code]
type = "scc"
files_glob = "src/**"

[analyzers.fixmes_and_todos]
type = "grep"
regex = "fixme|todo"
case_insensitive = true

[analyzers.clippy_commits]
type = "grep_commits"
regex = "clippy"
case_insensitive = true

[analyzers.dependabot]
type = "grep_commits"
regex = "Signed-off-by: dependabot\\[bot\\] <support@github\\.com>"
