[package]
name = "sapemu"
description = "SNES S-APU emulator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
human-panic = "1.1.4"
log = "0.4"
time = "0.3"

object = { version = "0.32", features = [
	"read",
	"elf",
], default-features = false }
simple_logger = "4.3.3"
bitflags = "2.5.0"

[dependencies.spcasm]
path = ".."
features = ["binaries"]

[dependencies.clap]
version = "4.4"
features = ["derive", "wrap_help", "string"]
