[book]
authors = ["kleines Filmröllchen"]
language = "en"
multilingual = false
src = "src"
title = "spcasm Manual"

[output.html]
[output.linkcheck]
optional = true
follow-web-links = true
# Because of how we include the README, linkcheck gets confused about this.
exclude = ['doc/src/SUMMARY\.md']
warning-policy = "ignore"

[output.pdf]
optional = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
marker = "* auto-gen TOC;\n{:toc}"
