[target.x86_64-unknown-linux-gnu]
# linker = "clang"
# Uncomment this if you want to link with mold.
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[registries.crates-io]
protocol = "sparse"
