name: spcasm Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy, rustfmt, cargo-fmt
          override: true
          default: true
    - name: Build
      run: cargo build --verbose --no-default-features
    - name: Run tests
      run: cargo test --verbose --no-default-features
    - name: Check style
      uses: actions-rs/clippy-check@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verbose --no-default-features
    - name: Check code format
      run: cargo fmt --check --verbose
