name: spcasm Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          default: true
    - name: Build
      run: cargo build --verbose --no-default-features
    - name: Run tests
      run: cargo test --verbose --no-default-features
    - name: Check style
      uses: LoliGothick/clippy-check@v.0.2.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        options: --verbose --no-default-features
        name: Check style
    - name: Check code format
      run: cargo fmt --check --verbose
